/*
This file was modified by the Flashtalking Service Suite
Version: 2.4.12
Tool: conceptulator
Date: January 25, 2023 at 10:22:11 AM
Logged Changes: 
*/
/*
This file was modified by the Flashtalking Service Suite
Version: 2.4.12
Tool: conceptulator
Date: January 18, 2023 at 12:06:35 PM
Logged Changes: 
*/
/*
This file was modified by the Flashtalking Service Suite
Version: 2.4.11
Tool: adrepair
Date: enero 14, 2023 at 03:35:15
Options Selected: {"alwaysClickTag":false,"multipleClickTag":false,"standardAd":false}
Logged Changes: f_api,f_cta,f_man,f_exl
*/
(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.bg = function() {
	this.initialize(img.bg);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1456,180);


(lib.card = function() {
	this.initialize(img.card);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1456,180);


(lib.resume = function() {
	this.initialize(img.resume);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,1456,180);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.txt2 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgFAHQgDgDAAgEQAAgDADgDQACgCADAAQAEAAACADQADACAAADQAAAEgDADQgCACgEAAQgDAAgCgCg");
	this.shape.setTransform(194.95,12.325);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgKAZIAAg+IABgCIANAAIABACIAAA8QAAAEADAAIACAAIABABIAAAKIgBAAIgHABQgNABAAgPg");
	this.shape_1.setTransform(192.275,9.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgSAUQgGgHAAgMQAAgMAHgHQAHgKAMABQALgBAGAJQAGAGAAAKIgBAGIgBABIgLAAIgUAAQABAMANAAQAIgBAGgCQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAABIAAAKIgBACQgHACgKAAQgNAAgIgIgAgIgGIANAAIAFAAIAAgBQAAgDgBgCQgDgDgFAAQgIAAgBAJg");
	this.shape_2.setTransform(187.625,10.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgHAbIgBgBIgSg0QAAAAABAAIAPAAIAAAAIAKAnIANgnIABAAIAMAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABgBAAIgSAzIgBABg");
	this.shape_3.setTransform(181.95,10.425);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgMAnIgBgBIAAg0IABAAIAMAAIABAAIAAA0IgBABgAgMgVQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIAKgPIACgBIANAAQABAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIgOAQIAAAAg");
	this.shape_4.setTransform(178.37,9.225);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAKAcIgBgBIAAgfQAAgKgIABQgFAAgDADIAAAlIgBABIgOAAIgBgBIAAgoIgBgMIABAAIAMAAIACAAIABAEQAGgGAIAAQAIAAAFAFQAFAFABANIAAAfIgCABg");
	this.shape_5.setTransform(173.1,10.35);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgTATQgHgHAAgMQAAgLAHgIQAIgIALAAQANAAAHAIQAHAIAAALQAAANgIAHQgHAJgMgBQgNABgGgKgAgIgKQgCAEAAAGQAAAHACAEQADAFAFAAQAFAAADgEQAEgEgBgIQAAgFgDgFQgDgFgFAAQgEAAgEAFg");
	this.shape_6.setTransform(164.3,10.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAaAcIgBgBIAAgfQAAgKgIABQgFAAgFADIABAGIAAAfIgBABIgMAAIgBgBIAAgfQAAgJgIAAQgFAAgEACIAAAmIgCABIgNAAIgBgBIAAgpIAAgKIABgBIALAAIABAAIABAEQAHgGAJAAQAJAAAEAHQAJgHAJAAQAIAAAFAFQAFAFABAMIAAAgIgBABg");
	this.shape_7.setTransform(156.4,10.35);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgGAnIgBgBIAAg0IABgBIANAAIABABIAAA0IgBABgAgGgXQgCgCAAgEQABgEACgCQACgDADAAQAEAAACADQACACABAEQgBAEgCACQgCACgEAAQgDAAgDgCg");
	this.shape_8.setTransform(150.25,9.275);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAKAbIgBgBIgJgSIgKATIgCAAIgNAAQAAAAgBAAQAAAAAAAAQAAAAAAAAQAAgBAAAAIARgaIgQgZQAAAAgBgBQAAAAAAAAQAAAAABAAQAAAAAAAAIAPAAIACAAIAIATIAKgTIABAAIAOAAQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAABAAAAIgQAZIASAaQAAAAAAABQAAAAAAAAQAAAAAAAAQgBAAAAAAg");
	this.shape_9.setTransform(146.075,10.425);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgTAfQgHgIAAgMQAAgLAHgIQAIgIALAAQANAAAHAIQAHAIAAALQAAANgIAIQgHAIgMAAQgNAAgGgJgAgIAAQgCAEAAAHQAAAIACAEQADAEAFAAQAFAAADgEQAEgEgBgIQAAgGgCgFQgEgDgFAAQgEAAgEADgAgHgVQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAAAIAKgQIABgBIAPAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgNAQIgDABg");
	this.shape_10.setTransform(140.35,9.275);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgOAcIgBgBIAAglIgBgPIABAAIAMAAIABABIABAFQAGgIALAAIABABIAAAOIgBAAQgGAAgFABIgFAEIAAAiIgBABg");
	this.shape_11.setTransform(135.475,10.35);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgZAmIAAg/IAAgIIAAAAQAOgFAKAAQAMAAAIAIQAGAIABALQAAANgKAJQgKAHgNAAIgCAAIAAATIgBABIgOABIgBgBgAgJgYIAAAdIADAAQAGAAAFgDQAFgEAAgIQAAgPgMAAIgHABg");
	this.shape_12.setTransform(130.2,11.45);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgUATQgGgHAAgMQAAgLAHgIQAIgIALAAQANAAAHAIQAHAIAAALQAAANgHAHQgIAJgMgBQgMABgIgKgAgHgKQgDAEgBAGQABAHADAEQADAFAEAAQAFAAADgEQADgEABgIQAAgFgDgFQgEgFgFAAQgFAAgCAFg");
	this.shape_13.setTransform(121.25,10.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgQAYQgGgFAAgJQAAgIAHgEQAGgEALgBIAGAAIAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgCgDgFAAQgIAAgHADQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIAAgMIABgBQAHgDAJAAQAMAAAGAGQAFAGAAAKIAAAVIAAAHIAAABQgNAEgKAAQgKABgGgFgAgHAKQAAAGAIABIAHgBIAAgMIgFgBQgKAAAAAHg");
	this.shape_14.setTransform(115.125,10.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgSAfQgGgHAAgMQAAgMAHgHQAHgJAMAAQALAAAGAIQAGAGAAAJIgBAHIgBABIgLAAIgUAAQABAMANAAQAIAAAGgDQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIAAAKIgBACQgHADgKAAQgNAAgIgJgAgIAFIANAAIAFAAIAAgBQAAgDgBgCQgDgDgFAAQgIAAgBAJgAgGgVQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAAAAAAAIAKgQIABgBIAPAAQAAAAABAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgOAQIgBABg");
	this.shape_15.setTransform(106.975,9.275);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgIAUIAAgaIgHAAIgBgBIAAgLIABgBIAHAAIABgNIABgBIAMgCQAAAAAAABIAAAPIAKAAIABABIAAALIgBABIgKAAIAAAWQAAAHAGAAIAEAAIAAABIAAAJIAAABQgFACgFAAQgOAAAAgQg");
	this.shape_16.setTransform(102.175,9.6667);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgQAYQgGgFAAgJQAAgIAHgEQAGgEALgBIAGAAIAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgCgDgFAAQgIAAgHADQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIAAgMIABgBQAHgDAJAAQAMAAAGAGQAFAGAAAKIAAAVIAAAHIAAABQgNAEgKAAQgKABgGgFgAgHAKQAAAGAIABIAHgBIAAgMIgFgBQgKAAAAAHg");
	this.shape_17.setTransform(97.375,10.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgQAYQgGgFAAgJQAAgIAHgEQAGgEALgBIAGAAIAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBgBAAQgCgDgFAAQgIAAgHADQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIAAgMIABgBQAHgDAJAAQAMAAAGAGQAFAGAAAKIAAAVIAAAHIAAABQgNAEgKAAQgKABgGgFgAgHAKQAAAGAIABIAHgBIAAgMIgFgBQgKAAAAAHg");
	this.shape_18.setTransform(89.075,10.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgOAcIgBgBIAAglIgBgPIABAAIAMAAIABABIABAFQAGgIALAAIABABIAAAOIgBAAQgGAAgFABIgFAEIAAAiIgBABg");
	this.shape_19.setTransform(84.625,10.35);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgGAnIgBgBIAAg0IABgBIANAAIABABIAAA0IgBABgAgGgXQgBgCAAgEQgBgEADgCQACgDADAAQAEAAACADQACACABAEQgBAEgCACQgCACgEAAQgDAAgDgCg");
	this.shape_20.setTransform(80.85,9.275);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgSAUQgGgHAAgMQAAgMAHgHQAHgKAMABQALgBAGAJQAGAGAAAKIgBAGIgBABIgLAAIgUAAQABAMANAAQAIgBAGgCQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAABIAAAKIgBACQgHACgKAAQgNAAgIgIgAgIgGIANAAIAFAAIAAgBQAAgDgBgCQgDgDgFAAQgIAAgBAJg");
	this.shape_21.setTransform(76.475,10.4);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgOAcIgBgBIAAglIgBgPIABAAIAMAAIABABIABAFQAGgIALAAIABABIAAAOIgBAAQgGAAgFABIgFAEIAAAiIgBABg");
	this.shape_22.setTransform(71.825,10.35);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgOAcIgBgBIAAglIgBgPIABAAIAMAAIABABIABAFQAGgIALAAIABABIAAAOIgBAAQgGAAgFABIgFAEIAAAiIgBABg");
	this.shape_23.setTransform(67.725,10.35);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgQAYQgGgFAAgJQAAgIAHgEQAGgEALgBIAGAAIAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgCgDgFAAQgIAAgHADQAAAAAAAAQAAAAgBAAQAAAAAAAAQAAAAAAAAIAAgMIABgBQAHgDAJAAQAMAAAGAGQAFAGAAAKIAAAVIAAAHIAAABQgNAEgKAAQgKABgGgFgAgHAKQAAAGAIABIAHgBIAAgMIgFgBQgKAAAAAHg");
	this.shape_24.setTransform(62.375,10.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgMAUQgIgHAAgNQAAgLAJgIQAIgIANAAQAHgBADACIABABIAAALIgBACQgEgCgFAAQgHAAgEAEQgEADAAAHQAAAIAEAEQAEADAHAAIAJgBIABABIAAALIgBABQgEACgIgBQgMABgIgJg");
	this.shape_25.setTransform(57.275,10.4);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgQAYQgGgFAAgJQAAgIAHgEQAGgEALgBIAGAAIAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAgBgBAAQgCgDgFAAQgIAAgHADQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAAAIAAgMIABgBQAHgDAJAAQAMAAAGAGQAFAGAAAKIAAAVIAAAHIAAABQgNAEgKAAQgKABgGgFgAgHAKQAAAGAIABIAHgBIAAgMIgFgBQgKAAAAAHg");
	this.shape_26.setTransform(49.175,10.4);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgXAHIAAghIABgBIANAAIABABIAAAfQAAAKAIAAQAEAAAEgEIAAglIABgBIAOAAIAAABIAAApIABALIgBABIgMAAIgBgBIAAgDQgHAFgIAAQgSAAAAgVg");
	this.shape_27.setTransform(43.425,10.475);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgSAaIgBgBIAAgNQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAHAEAJAAQAHAAAAgEQAAgDgHgCQgJgEgEgDQgEgEAAgGQAAgIAFgEQAGgFAKAAQAJgBAFADIABABIAAAMQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAAAQgHgDgIAAQgFAAAAAEQAAACAGADQAKAEAEADQAEAEAAAGQAAAIgGAFQgGAFgKgBQgKAAgGgCg");
	this.shape_28.setTransform(37.975,10.4);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgQAYQgGgFAAgJQAAgIAHgEQAGgEALgBIAGAAIAAAAQAAgBAAAAQAAgBAAAAQAAgBgBAAQAAgBgBAAQgCgDgFAAQgIAAgHADQAAAAAAAAQAAAAAAAAQgBAAAAAAQAAAAAAAAIAAgMIABgBQAHgDAJAAQAMAAAGAGQAFAGAAAKIAAAVIAAAHIAAABQgNAEgKAAQgKABgGgFgAgHAKQAAAGAIABIAHgBIAAgMIgFgBQgKAAAAAHg");
	this.shape_29.setTransform(30.025,10.4);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgSAUQgGgHAAgMQAAgMAHgHQAHgKAMABQALgBAGAJQAGAGAAAKIgBAGIgBABIgLAAIgUAAQABAMANAAQAIgBAGgCQAAAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAABIAAAKIgBACQgHACgKAAQgNAAgIgIgAgIgGIANAAIAFAAIAAgBQAAgDgBgCQgDgDgFAAQgIAAgBAJg");
	this.shape_30.setTransform(21.875,10.4);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgGAbIgBgBIgSg0QgBAAABAAIAOAAIABAAIALAnIAMgnIAAAAIANAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAABgBAAIgSAzIgBABg");
	this.shape_31.setTransform(16.2,10.425);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgSAUQgGgHAAgMQAAgMAHgHQAHgKAMABQALgBAGAJQAGAGAAAKIgBAGIgBABIgLAAIgUAAQABAMANAAQAIgBAGgCQAAAAAAAAQAAAAABAAQAAAAAAAAQAAAAAAABIAAAKIgBACQgHACgKAAQgNAAgIgIgAgIgGIANAAIAFAAIAAgBQAAgDgBgCQgDgDgFAAQgIAAgBAJg");
	this.shape_32.setTransform(10.575,10.4);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgWAkIgBgBIAAhFIABgBIAOAAIAAABIAAA4IAfAAIABABIgCAMIgBABg");
	this.shape_33.setTransform(5.175,9.55);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt2, new cjs.Rectangle(0,0,220,17.8), null);


(lib.txt1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgKALQgEgEAAgHQAAgGAEgFQAEgDAGAAQAHgBAEAFQAEAEAAAGQAAAHgEAEQgEAEgHAAQgGAAgEgEg");
	this.shape.setTransform(187.175,42.55);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgcA3QgOgNAAgWQAAgVAOgNQAPgPAXAAIAHABIAAglIABgBIAXAAIABABIAABtIABAOIgBABQgSAHgTAAQgUABgNgMgAgIgBQgIAHAAAMQAAAOAHAGQAHAHAKAAQAFAAAEgCIAAgxIgHgBQgLAAgHAGg");
	this.shape_1.setTransform(180.275,37.45);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgoALIAAg4QAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAXAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAA1QAAAQAOAAQAIABAGgGIAAhAQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAWAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAABFIACATQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAAAIgUAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAgBIgBgFQgKAJgOAAQggAAAAgkg");
	this.shape_2.setTransform(170.875,39.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AghAhQgMgNAAgUQAAgTANgOQANgOAUAAQAVAAAMAOQAMAOAAATQAAAVgNAOQgMANgVAAQgVAAgMgPgAgNgTQgGAIAAALQAAAMAGAHQAGAHAIAAQAIABAFgIQAGgGAAgNQAAgKgFgIQgGgHgJgBQgHAAgGAHg");
	this.shape_3.setTransform(161.1,39.3);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgRApIAAhpQAAAAAAgBQAAAAAAAAQABAAAAAAQABgBAAAAIAVAAQAAAAABABQAAAAAAAAQABAAAAAAQAAABAAAAIAABnQAAAGAGABIAEAAIAAABIAAAQIgBACQgEABgHAAQgXABAAgag");
	this.shape_4.setTransform(154.3,37.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgbAuQgSgQAAgeQAAgbASgRQATgSAdAAQARAAAHADIABADIAAAUQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBgBQgIgEgQAAQgSAAgKALQgLALAAARQAAAUANAKQALAJAQAAQANAAAJgDQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAATQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQgJADgQAAQgbAAgSgQg");
	this.shape_5.setTransform(146.85,37.85);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgfAhQgKgNAAgTQAAgTALgOQANgPAUAAQATAAALANQAJAMAAAPIgBAMIgCABIgSABIgjAAQABATAYAAQANAAAJgEQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAABIAAASIgBACQgLAFgRAAQgXAAgNgPgAgPgKIAYAAIAJAAIAAgCQgBgEgDgFQgEgFgIgBQgOAAgDARg");
	this.shape_6.setTransform(133.75,39.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgLAuQgBAAAAAAQAAAAgBAAQAAgBAAAAQgBAAAAgBIgehYQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAYAAQAAAAAAAAQABAAAAAAQAAABAAAAQABAAAAAAQAOAvADATIAAAAQADgNARg1IABgBIAWAAQAAAAAAAAQABAAAAABQAAAAAAAAQAAABAAAAIgfBXQAAABAAAAQgBAAAAABQAAAAgBAAQAAAAAAAAg");
	this.shape_7.setTransform(124.9867,39.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgKBBQgBAAAAAAQgBAAAAAAQAAAAAAgBQAAAAAAAAIAAhYQAAgBAAAAQAAAAAAAAQAAgBABAAQAAAAAAAAIAWAAQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAABIAABYQAAAAAAAAQgBABAAAAQAAAAAAAAQgBAAAAAAgAgKgnQgDgEAAgHQAAgGAEgEQAEgEAFAAQAHAAADAEQAEAEAAAGQAAAHgEAEQgEAEgGAAQgGAAgEgEg");
	this.shape_8.setTransform(118.625,37.375);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgPAiIAAgtIgLAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAgSQAAgBAAAAQAAgBAAAAQAAAAABAAQAAAAABAAIAKAAQABgPABgIIACgBIAVgDQAAAAAAAAQAAAAABAAQAAAAAAAAQAAABAAAAIgBAaIARAAQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAATQAAAAgBAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgSAAIAAAmQAAANAKAAIAGgBQAAAAABAAQAAAAAAAAQAAAAAAAAQABABAAAAIAAAPQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAQgHACgJAAQgZABAAgbg");
	this.shape_9.setTransform(113.6,38.05);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgbApQgLgJAAgPQAAgPAMgGQALgIASAAIALABIAAgCQAAgEgDgDQgFgFgJAAQgNABgMAFQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgTQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAMgGAQAAQATAAAKALQAKAKAAARIAAAiIAAANIAAACQgWAIgSAAQgQAAgKgHgAgNARQAAALAPAAQAGAAAGgCIAAgTIgKgBQgRAAAAALg");
	this.shape_10.setTransform(106.275,39.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgfAhQgKgNAAgTQAAgTALgOQANgPAUAAQATAAALANQAJAMAAAPIgBAMIgBABIgTABIgjAAQABATAYAAQAMAAAKgEQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAABIAAASIgBACQgLAFgRAAQgXAAgNgPgAgPgKIAXAAIAJAAIAAgCQAAgEgDgFQgEgFgIgBQgPAAgCARg");
	this.shape_11.setTransform(97.65,39.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgYAvQgBAAAAAAQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAg/IgBgZQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAUAAQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAQACAEAAAGQALgOASAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAAAYQAAAAAAAAQAAAAAAAAQAAAAgBAAQAAABAAAAQgKAAgIACQgHACgCAEIAAA5QAAABAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAg");
	this.shape_12.setTransform(90.525,39.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgbAuQgSgQAAgeQAAgbASgRQATgSAdAAQARAAAHADIABADIAAAUQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAgBgBQgIgEgPAAQgTAAgKALQgLALAAARQABAUANAKQAJAJARAAQANAAAJgDQABAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAATQAAABAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQgJADgQAAQgbAAgSgQg");
	this.shape_13.setTransform(82.15,37.85);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgfAhQgKgNAAgTQAAgTALgOQANgPAUAAQATAAALANQAJAMAAAPIgBAMIgCABIgTABIgiAAQABATAYAAQANAAAJgEQABAAAAAAQAAAAAAAAQAAAAAAAAQABAAAAABIAAASIgCACQgLAFgRAAQgXAAgNgPgAgPgKIAYAAIAJAAIAAgCQAAgEgEgFQgEgFgIgBQgOAAgDARg");
	this.shape_14.setTransform(69.05,39.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgpA+IgBgCIAAh9QAAAAAAAAQAAAAABAAQAAAAAAAAQAAgBABAAIAWAAQABAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIAAAmQAIgDAIAAQATAAAMAOQAMAMAAARQAAAagRAOQgQANgVgBQgQAAgOgEgAgQgFIAAAxIAHABQAKAAAIgHQAIgHAAgOQAAgMgHgGQgGgFgJAAIgLABg");
	this.shape_15.setTransform(59.925,37.45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AghAhQgMgNAAgUQAAgTANgOQANgOAUAAQAVAAAMAOQAMAOAAATQAAAVgNAOQgMANgVAAQgVAAgMgPgAgNgTQgGAIAAALQAAAMAGAHQAGAHAIAAQAIABAFgIQAGgGAAgNQAAgKgFgIQgGgHgJgBQgHAAgGAHg");
	this.shape_16.setTransform(49.95,39.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgcA3QgOgNAAgWQAAgVAOgNQAPgPAXAAIAHABIAAglIABgBIAXAAIABABIAABtIABAOIgBABQgSAHgTAAQgUABgNgMgAgIgBQgIAHAAAMQAAAOAHAGQAHAHAKAAQAFAAAEgCIAAgxIgHgBQgLAAgHAGg");
	this.shape_17.setTransform(40.025,37.45);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAfA9QAAAAAAgBQgBAAAAAAQAAAAAAAAQAAgBgBAAIgJgbIgqAAIgJAbQAAAAAAABQAAAAAAAAQgBAAAAAAQAAABgBAAIgVAAQgBAAAAgBQAAAAAAAAQgBAAAAgBQAAAAAAAAIAlhqQACgEAAgIQAAAAAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAIAdAAIABABIAqB2QABAAAAABQAAAAgBAAQAAAAAAAAQAAABgBAAgAANAJIgOgvIgOAvIAcAAIAAAAg");
	this.shape_18.setTransform(30.0013,37.85);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgbApQgLgJAAgPQAAgPAMgGQALgIASAAIALABIAAgCQAAgEgDgDQgFgFgJAAQgNABgMAFQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgTQAAAAAAgBQAAAAAAAAQAAgBABAAQAAAAAAAAQAMgGAQAAQATAAAKALQAKAKAAARIAAAiIAAANIAAACQgWAIgSAAQgQAAgKgHgAgNARQAAALAPAAQAGAAAGgCIAAgTIgKgBQgRAAAAALg");
	this.shape_19.setTransform(16.225,39.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AARAvQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIAAg0QAAgRgOAAQgIABgGAFIAAA/QAAABgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgXAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAgBIAAhEIgBgUQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAUAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIACAHQALgKAOAAQANAAAIAIQAKAJAAAUIAAA2QAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_20.setTransform(7.1438,39.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AASAyQgHgJgBgOQAAgQAKgKQAJgIANAAQAPAAAIAJQAIAJAAAPQAAAOgIAJQgIALgPAAQgPAAgJgKgAAeAaQAAARANAAQAKAAABgRQAAgRgMAAQgMAAAAARgAgxA6IgBAAIABgBIBQhxIADgBIAPAAQABAAAAAAQABAAAAAAQAAAAAAAAQgBAAAAABIhQBxIgDABgAhAgBQgIgJAAgPQAAgQAKgJQAIgJANAAQAPAAAJAJQAHAJAAAQQAAANgHAKQgJAKgPAAQgQAAgHgJgAg0gZQgBARAMAAQAMAAAAgRQAAgRgMAAQgMAAABARg");
	this.shape_21.setTransform(202.9,14.925);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AglA1IgBgCIAAgVQAAAAAAgBQAAAAAAAAQABAAAAAAQAAAAAAAAQAOAIAQAAQAUAAAAgPQAAgKgLgFQgLgFgbgCQAAAAAAAAQgBAAAAAAQAAAAAAAAQgBgBAAAAIAAgKIAOguIABgBIA5AAQAAAAABAAQAAAAAAAAQAAAAAAAAQAAAAAAABIgFAUQAAAAgBAAQAAAAAAABQAAAAAAAAQgBAAAAAAIglAAIgEARQA0AFAAAiQAAASgNAKQgNALgTAAQgTAAgMgGg");
	this.shape_22.setTransform(190.8,15.025);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAIA6QAAAAAAAAQAAAAgBAAQAAAAAAgBQAAAAAAAAIAAgZIgzAAQAAAAAAAAQgBAAAAgBQAAAAAAAAQAAAAAAAAIAAgRIABgDIAshDIADgBIAbAAQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIAABDIAOAAQAAAAABAAQAAAAAAAAQAAAAAAABQAAAAAAAAIgCATIgCABIgLAAIAAAZQAAAAAAAAQAAABAAAAQAAAAgBAAQAAAAAAAAgAgTALIAaAAIAAgMIABghIAAAAQgFAJgWAkg");
	this.shape_23.setTransform(181.58,14.925);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAtAvQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAg0QAAgRgOgBQgJAAgHAHIABAKIAAA1QAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgVAAQgBAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAg1QAAgQgOgBQgIABgHAFIAABAQAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgXAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAhGIgBgSQAAAAAAgBQAAAAAAgBQAAAAABAAQAAAAABAAIATAAIACABIACAHQAMgKAOAAQAQAAAHAMQAOgMAQAAQANAAAJAIQAJAKAAATIAAA3QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAAAAAg");
	this.shape_24.setTransform(165.395,16.05);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgbAoQgLgIAAgPQAAgOAMgIQALgHASAAIALABIAAgCQAAgEgDgDQgFgEgJgBQgNAAgMAGQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgTQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAQAMgGAQAAQATAAAKALQAKAKAAARIAAAjIAAAMIAAABQgWAJgSAAQgQAAgKgIgAgNARQAAALAPAAQAGAAAGgCIAAgTIgKgBQgRAAAAALg");
	this.shape_25.setTransform(153.125,16.15);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgqBAIAAhsIAAgMIABgBQAWgIAQAAQAWABANAOQALAMAAASQAAAXgRAOQgQANgWABIgEgBIAAAfQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgXADQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAgBAAAAgAgQgpIAAAxIAGABQAKAAAIgGQAJgHAAgOQAAgZgWABQgGAAgFABg");
	this.shape_26.setTransform(144.375,17.9);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgoALIAAg4QAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAXAAQAAAAAAAAQAAAAAAAAQABABAAAAQAAAAAAAAIAAA1QAAARAOAAQAIAAAGgGIAAhAQAAAAAAAAQAAAAAAgBQABAAAAAAQAAAAABAAIAWAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAABGIACATQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAIgUAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgBgGQgKAJgOAAQggAAAAgkg");
	this.shape_27.setTransform(134.475,16.25);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgiAhQgLgNABgUQgBgTANgOQANgOATAAQAWAAANAOQALANgBAUQAAAVgMAOQgNANgUAAQgVAAgNgPgAgNgSQgFAHAAALQAAAMAFAHQAFAHAIABQAJAAAFgIQAGgGgBgNQABgKgFgHQgFgJgKABQgIgBgFAIg");
	this.shape_28.setTransform(124.7,16.15);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgqBAIAAhsIAAgMIABgBQAWgIAQAAQAWABANAOQALAMAAASQAAAXgRAOQgQANgWABIgEgBIAAAfQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgXADQgBAAAAgBQAAAAAAAAQgBAAAAAAQAAgBAAAAgAgQgpIAAAxIAGABQAKAAAIgGQAJgHAAgOQAAgZgWABQgGAAgFABg");
	this.shape_29.setTransform(115.275,17.9);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgfArIgBgDIAAgUQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAQALAIAQAAQALAAAAgHQAAgFgNgFQgPgFgGgGQgGgHAAgKQAAgMAIgIQAKgJARAAQAQAAAIAEIABACIAAATQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQgKgFgOAAQgKAAAAAGQAAAEAMAGQAQAGAHAFQAGAIAAAKQAAANgKAIQgKAIgRAAQgRAAgKgFg");
	this.shape_30.setTransform(102.975,16.15);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgfAhQgKgNAAgTQAAgTALgOQANgPAUAAQATAAALANQAJALAAAQIgBALIgBACIgTABIgjAAQABATAYAAQAMAAAKgEQABAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAASIgBADQgLAFgRAAQgXAAgNgPgAgPgKIAXAAIAJAAIAAgCQAAgFgDgEQgEgFgIAAQgPAAgCAQg");
	this.shape_31.setTransform(94.95,16.15);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgPAiIAAgtIgLAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAgSQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBABAAIAKAAQABgOABgIIACgBIAVgEQAAAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIgBAZIARAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAATQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgSAAIAAAmQAAAMAKAAIAGgBQAAAAABABQAAAAAAAAQAAAAAAAAQABABAAAAIAAAPQAAABgBAAQAAABAAAAQAAAAAAABQgBAAAAAAQgHACgJABQgZgBAAgag");
	this.shape_32.setTransform(87.6,14.9);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AARAvQAAAAgBAAQAAAAAAAAQgBgBAAAAQAAAAAAAAIAAg0QAAgRgOgBQgIAAgGAHIAAA/QAAAAgBAAQAAAAAAABQAAAAgBAAQAAAAAAAAIgXAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAhFIgBgUQAAAAAAAAQAAAAAAgBQAAAAAAAAQABAAAAAAIAUAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAAAIACAHQALgKAOAAQANAAAIAHQAKAKAAAVIAAA2QAAAAAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAg");
	this.shape_33.setTransform(80.0438,16.05);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgbAoQgLgIAAgPQAAgOAMgIQALgHASAAIALABIAAgCQAAgEgDgDQgFgEgJgBQgNAAgMAGQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAAgTQAAAAAAgBQAAAAAAAAQAAAAABgBQAAAAAAAAQAMgGAQAAQATAAAKALQAKAKAAARIAAAjIAAAMIAAABQgWAJgSAAQgQAAgKgIgAgNARQAAALAPAAQAGAAAGgCIAAgTIgKgBQgRAAAAALg");
	this.shape_34.setTransform(70.475,16.15);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgcA2QgOgMAAgWQAAgVAOgNQAPgPAXAAIAHABIAAglIABAAIAXAAIABAAIAABtIABAOIgBABQgSAIgTAAQgUgBgNgMgAgIgBQgIAHAAAMQAAAOAHAGQAHAHAKgBQAFAAAEgBIAAgxIgHgBQgLAAgHAGg");
	this.shape_35.setTransform(61.225,14.3);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgoALIAAg4QAAAAAAAAQAAAAABgBQAAAAAAAAQAAAAABAAIAXAAQAAAAAAAAQAAAAABAAQAAABAAAAQAAAAAAAAIAAA1QAAARAOAAQAIAAAGgGIAAhAQAAAAAAAAQAAAAAAgBQAAAAABAAQAAAAABAAIAWAAQAAAAAAAAQABAAAAAAQAAABAAAAQAAAAAAAAIAABGIACATQAAAAAAAAQgBAAAAABQAAAAAAAAQgBAAAAAAIgUAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQgBAAAAAAIgBgGQgKAJgOAAQggAAAAgkg");
	this.shape_36.setTransform(51.825,16.25);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgPAiIAAgtIgLAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIAAgSQAAgBAAAAQAAgBAAAAQAAAAABAAQAAgBAAAAIALAAQABgOABgIIACgBIAVgEQAAAAAAABQAAAAABAAQAAAAAAAAQAAABAAAAIgBAZIARAAQAAAAABABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAATQAAAAAAAAQAAAAAAABQAAAAAAAAQAAAAgBAAIgRAAIAAAmQAAAMAKAAIAGgBQAAAAABABQAAAAAAAAQAAAAAAAAQAAABAAAAIAAAPQAAABAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQgHACgJABQgZgBAAgag");
	this.shape_37.setTransform(44.05,14.9);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgfArIgBgDIAAgUQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAQALAIAQAAQALAAAAgHQAAgFgNgFQgPgFgGgGQgGgHAAgKQAAgMAIgIQAKgJARAAQAQAAAIAEIABACIAAATQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQgKgFgOAAQgKAAAAAGQAAAEAMAGQAQAGAHAFQAGAIAAAKQAAANgKAIQgKAIgRAAQgRAAgKgFg");
	this.shape_38.setTransform(37.875,16.15);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgeAhQgLgNAAgTQAAgTAMgOQAMgPAUAAQATAAALANQAJALAAAQIgBALIgBACIgUABIgjAAQACATAYAAQAMAAALgEQAAAAAAAAQAAAAAAAAQAAAAAAAAQAAAAAAAAIAAASIAAADQgMAFgRAAQgXAAgMgPgAgPgKIAXAAIAJAAIAAgCQAAgFgCgEQgFgFgIAAQgOAAgDAQg");
	this.shape_39.setTransform(29.85,16.15);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AgfArIgBgDIAAgUQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABAAQALAIAQAAQALAAAAgHQAAgFgNgFQgPgFgGgGQgGgHAAgKQAAgMAIgIQAKgJARAAQAQAAAIAEIABACIAAATQAAABAAAAQAAAAgBAAQAAAAAAAAQAAAAgBAAQgKgFgOAAQgKAAAAAGQAAAEAMAGQAQAGAHAFQAGAIAAAKQAAANgKAIQgKAIgRAAQgRAAgKgFg");
	this.shape_40.setTransform(18.175,16.15);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgpAtQgQgRAAgcQAAgaAQgRQAQgSAZAAQAbAAAPASQAPARABAaQAAAcgQARQgRASgZAAQgagBgPgRgAgWgcQgIAKAAASQAAASAIAKQAIALAOAAQAPAAAIgKQAJgLAAgSQgBgRgIgLQgJgLgOAAQgOAAgIALg");
	this.shape_41.setTransform(8.45,14.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.txt1, new cjs.Rectangle(0,0,219,50.3), null);


(lib.resume_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.resume();
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.resume_1, new cjs.Rectangle(0,0,728,90), null);


(lib.logo = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABnC+QgHgJAAgQQAAgRAHgKQAHgKAMAAQAMgBAGAKQAFAHAAALIgBALQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgNAAIgRAAQABAJADAFQAEAEAJAAQAFAAAFgCIABABIAAALIgBADQgFACgJAAQgPAAgHgKgABxCbIAMAAIAEgBIAAgBQAAgFgBgDQgDgEgEAAQgHAAgBAOgAApDGIgBgBIAAheIABgBIAPAAIABABIAAAZIAHAAQALgBAIAJQAHAIAAARQAAASgJALQgJAKgPAAQgJAAgHgCgAA5CPIAAAqIACAAQAGAAADgFQAFgHABgMQgBgKgDgFQgDgDgGAAIgEAAgAgNC+QgGgKgBgQQAAgRAHgJQAHgLALABQAMAAAHAJQAHAKAAARQAAARgHAJQgHAKgMAAQgMAAgGgKgAgDCkQAAAKACAGQABAFAFAAQAJABAAgWQAAgLgBgFQgDgGgFAAQgIAAAAAWgAhGC/QgJgJAAgSQAAgQAJgKQAIgKAOAAIADAAIAAgZIABgBIAPAAIAAABIAABRIABAKIgBABQgJAFgLAAQgOAAgHgJgAg6CTQgEAGAAALQAAAKAEAGQAEAEAFAAIAEAAIAAgpIgEgBQgFAAgEAFgAhhDHIgBgBIgGgXIgTAAIgGAXIgBABIgNAAQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAAAIAThRIABgIIAAgBIAUAAIABABIAVBZQABAAAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAgAh5CgIAPAAIgFgSIgCgTIgBAAIgHAlgAAmjHIBrAAIAAEAgAAXA5IgUg0IgxAAIAuhuIBECigAiQjHIBrAAIhrEAg");
	this.shape.setTransform(14.5,20);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.logo, new cjs.Rectangle(0,0,29,40), null);


(lib.cta = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYAjQgJgHAAgOQAAgMAKgGQAKgHAPABIAKAAIAAgCQAAgDgDgCQgEgFgHAAQgMAAgKAFQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgQIABgCQAKgEAOgBQARABAJAIQAHAKABAOIAAAeIAAAMIAAABQgTAGgPAAQgOABgKgHgAgLAOQAAAKANAAIAKgBIAAgSIgIAAQgPAAAAAJg");
	this.shape.setTransform(110.65,21.45);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgVApQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2IgBgWIACgBIARAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAQABAEABAFQAJgMAQAAIABABIAAAUQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAQgIAAgHACQgHACgBADIAAAyQgBABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_1.setTransform(104.55,21.375);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgdAcQgKgLAAgRQAAgRALgLQALgMARgBQATABALAMQAKALAAARQAAASgMAMQgLAMgRgBQgSAAgLgNgAgLgQQgFAGAAAKQAAAKAEAHQAFAGAHAAQAIAAAEgGQAFgGAAgLQAAgJgEgGQgFgHgIAAQgHAAgEAGg");
	this.shape_2.setTransform(97.025,21.45);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgeAyQgJgHAAgKQAAgIAOgMQgEgGABgHQAAgEACgFQgLgHABgOQgBgMAKgIQAIgHAQAAIAOABIAEAAIAWAAIABABIAAAPIgBABIgLAAQACAEAAAGQAAAMgJAHQgIAHgNAAIgGgBIgBAEQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABIAQABQAgABAAAWQAAANgMAIQgMAJgSAAQgTAAgKgIgAgSAbIgBAEQAAAEAFADQAFAEAJAAQAKAAAFgEQAFgCAAgFQAAgHgQgBIgRAAIgFAEgAgPgeQAAAFAEADQADADAFAAQAKAAAAgLQAAgLgKAAQgMAAAAALg");
	this.shape_3.setTransform(88.7,23.125);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgXAjQgKgHAAgOQAAgMAKgGQAKgHAQABIAJAAIAAgCQAAgDgCgCQgFgFgIAAQgLAAgKAFQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgQIABgCQAKgEAOgBQARABAIAIQAIAKAAAOIAAAeIABAMIgBABQgSAGgQAAQgNABgJgHgAgLAOQAAAKANAAIAKgBIAAgSIgIAAQgPAAAAAJg");
	this.shape_4.setTransform(80.2,21.45);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgVApQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2IAAgWIABgBIARAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAQACAEgBAFQAKgMAPAAIABABIAAAUQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAQgIAAgHACQgHACgBADIgBAyQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_5.setTransform(70.65,21.375);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgXAjQgKgHAAgOQAAgMAKgGQAKgHAQABIAJAAIAAgCQAAgDgCgCQgFgFgIAAQgLAAgKAFQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgQIABgCQAKgEAOgBQARABAJAIQAHAKAAAOIAAAeIABAMIgBABQgSAGgPAAQgOABgJgHgAgLAOQAAAKANAAIAKgBIAAgSIgIAAQgPAAAAAJg");
	this.shape_6.setTransform(63.2,21.45);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgVApQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBgWIABgBIASAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAQACAEAAAFQAJgMAQAAIABABIAAAUQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAQgIAAgHACQgGACgCADIAAAyQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_7.setTransform(57.1,21.375);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgkA3IAAhdIgBgLIABgBQAUgGAOAAQATAAALAMQAKAKAAARQAAAUgPAMQgOALgUAAIgDAAIAAAcIgBABIgUACQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBgAgOgkIAAArIAFABQAJgBAHgFQAIgGAAgMQAAgVgTAAQgFgBgFACg");
	this.shape_8.setTransform(49.725,23);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AAmApQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAgtQAAgPgMAAQgIAAgGAGIAAAJIAAAtQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgTAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAgtQAAgPgMAAQgHAAgHAFIAAA3QAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgTAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg8IAAgQQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIARAAIACABIABAGQAKgJANAAQAOAAAGAKQAMgKAOAAQAMAAAHAHQAJAIAAARIAAAvQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_9.setTransform(38.4,21.375);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgdAcQgKgLAAgRQAAgRALgLQALgMARgBQATABALAMQAKALAAARQAAASgMAMQgLAMgRgBQgSAAgLgNgAgLgQQgFAGAAAKQAAAKAEAHQAFAGAHAAQAIAAAEgGQAFgGAAgLQAAgJgEgGQgFgHgIAAQgHAAgEAGg");
	this.shape_10.setTransform(27.375,21.45);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgXApQgQgPAAgaQAAgXAQgPQAQgPAZAAQAPAAAGACIABACIAAASQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAQgIgEgNAAQgQAAgJAKQgJAJAAAPQAAARALAJQAJAIAOAAQAMAAAIgCQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIAAAQQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAQgIADgOAAQgYAAgPgNg");
	this.shape_11.setTransform(18.725,20.175);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f().s("#FFFFFF").ss(3,1,1).p("AmujHINcAAQBbAABBA6QBAA7AABSIAAAAQAABThAA7QhBA6hbAAItcAAQhaAAhBg6QhAg7AAhTIAAAAQAAhSBAg7QBBg6BaAAg");
	this.shape_12.setTransform(65,20);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#000000").s().p("AgYAjQgJgHAAgOQAAgMAKgGQAKgHAPABIAKAAIAAgCQAAgDgDgCQgEgFgHAAQgMAAgKAFQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgQIABgCQAKgEAOgBQARABAJAIQAHAKABAOIAAAeIAAAMIAAABQgTAGgPAAQgOABgKgHgAgLAOQAAAKANAAIAKgBIAAgSIgIAAQgPAAAAAJg");
	this.shape_13.setTransform(110.65,21.45);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#000000").s().p("AgVApQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2IgBgWIACgBIARAAQAAAAABAAQAAAAAAAAQAAAAABABQAAAAAAAAQABAEABAFQAJgMAQAAIABABIAAAUQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAQgIAAgHACQgHACgBADIAAAyQgBABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_14.setTransform(104.55,21.375);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AgdAcQgKgLAAgRQAAgRALgLQALgMARgBQATABALAMQAKALAAARQAAASgMAMQgLAMgRgBQgSAAgLgNgAgLgQQgFAGAAAKQAAAKAEAHQAFAGAHAAQAIAAAEgGQAFgGAAgLQAAgJgEgGQgFgHgIAAQgHAAgEAGg");
	this.shape_15.setTransform(97.025,21.45);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#000000").s().p("AgeAyQgJgHAAgKQAAgIAOgMQgEgGABgHQAAgEACgFQgLgHABgOQgBgMAKgIQAIgHAQAAIAOABIAEAAIAWAAIABABIAAAPIgBABIgLAAQACAEAAAGQAAAMgJAHQgIAHgNAAIgGgBIgBAEQAAAAABABQAAAAAAABQAAAAABABQAAAAAAABIAQABQAgABAAAWQAAANgMAIQgMAJgSAAQgTAAgKgIgAgSAbIgBAEQAAAEAFADQAFAEAJAAQAKAAAFgEQAFgCAAgFQAAgHgQgBIgRAAIgFAEgAgPgeQAAAFAEADQADADAFAAQAKAAAAgLQAAgLgKAAQgMAAAAALg");
	this.shape_16.setTransform(88.7,23.125);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#000000").s().p("AgXAjQgKgHAAgOQAAgMAKgGQAKgHAQABIAJAAIAAgCQAAgDgCgCQgFgFgIAAQgLAAgKAFQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgQIABgCQAKgEAOgBQARABAIAIQAIAKAAAOIAAAeIABAMIgBABQgSAGgQAAQgNABgJgHgAgLAOQAAAKANAAIAKgBIAAgSIgIAAQgPAAAAAJg");
	this.shape_17.setTransform(80.2,21.45);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#000000").s().p("AgVApQAAAAgBAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg2IAAgWIABgBIARAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAQACAEgBAFQAKgMAPAAIABABIAAAUQAAABAAAAQAAAAAAAAQAAAAAAAAQgBAAAAAAQgIAAgHACQgHACgBADIgBAyQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_18.setTransform(70.65,21.375);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#000000").s().p("AgXAjQgKgHAAgOQAAgMAKgGQAKgHAQABIAJAAIAAgCQAAgDgCgCQgFgFgIAAQgLAAgKAFQAAAAAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAAgQIABgCQAKgEAOgBQARABAJAIQAHAKAAAOIAAAeIABAMIgBABQgSAGgPAAQgOABgJgHgAgLAOQAAAKANAAIAKgBIAAgSIgIAAQgPAAAAAJg");
	this.shape_19.setTransform(63.2,21.45);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#000000").s().p("AgVApQAAAAgBAAQAAAAAAgBQgBAAAAAAQAAAAAAgBIAAg2IgBgWIABgBIASAAQAAAAABAAQAAAAAAAAQABAAAAABQAAAAAAAAQACAEAAAFQAJgMAQAAIABABIAAAUQAAABgBAAQAAAAAAAAQAAAAAAAAQgBAAAAAAQgIAAgHACQgGACgCADIAAAyQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_20.setTransform(57.1,21.375);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#000000").s().p("AgkA3IAAhdIgBgLIABgBQAUgGAOAAQATAAALAMQAKAKAAARQAAAUgPAMQgOALgUAAIgDAAIAAAcIgBABIgUACQAAAAAAAAQgBAAAAAAQAAgBAAAAQAAAAAAgBgAgOgkIAAArIAFABQAJgBAHgFQAIgGAAgMQAAgVgTAAQgFgBgFACg");
	this.shape_21.setTransform(49.725,23);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#000000").s().p("AAmApQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAgtQAAgPgMAAQgIAAgGAGIAAAJIAAAtQAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgTAAQAAAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAgtQAAgPgMAAQgHAAgHAFIAAA3QAAABAAAAQAAAAAAAAQAAABAAAAQgBAAAAAAIgTAAQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAAAAAgBIAAg8IAAgQQAAAAAAAAQAAgBAAAAQAAAAAAAAQABAAAAAAIARAAIACABIABAGQAKgJANAAQAOAAAGAKQAMgKAOAAQAMAAAHAHQAJAIAAARIAAAvQAAABgBAAQAAAAAAAAQAAABAAAAQgBAAAAAAg");
	this.shape_22.setTransform(38.4,21.375);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#000000").s().p("AgdAcQgKgLAAgRQAAgRALgLQALgMARgBQATABALAMQAKALAAARQAAASgMAMQgLAMgRgBQgSAAgLgNgAgLgQQgFAGAAAKQAAAKAEAHQAFAGAHAAQAIAAAEgGQAFgGAAgLQAAgJgEgGQgFgHgIAAQgHAAgEAGg");
	this.shape_23.setTransform(27.375,21.45);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#000000").s().p("AgXApQgQgPAAgaQAAgXAQgPQAQgPAZAAQAPAAAGACIABACIAAASQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAQgIgEgNAAQgQAAgJAKQgJAJAAAPQAAARALAJQAJAIAOAAQAMAAAIgCQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIAAAQQAAABAAAAQAAAAAAABQAAAAgBAAQAAAAAAAAQgIADgOAAQgYAAgPgNg");
	this.shape_24.setTransform(18.725,20.175);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AmuDIQhaAAhBg6QhAg7AAhTIAAAAQAAhSBAg7QBBg6BaAAINcAAQBaAABCA6QBAA7AABSIAAAAQAABThAA7QhCA6haAAg");
	this.shape_25.setTransform(65,20);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("EhdKAT4MAAAgnvMC6VAAAMAAAAnvg");
	this.shape_26.setTransform(38.7,24.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).to({state:[{t:this.shape_25},{t:this.shape_12},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13}]},1).to({state:[{t:this.shape_25},{t:this.shape_12},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13}]},1).to({state:[{t:this.shape_26}]},1).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-557.6,-102.7,1192.6,254.39999999999998);


(lib.card_1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Capa_1
	this.instance = new lib.card();
	this.instance.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.card_1, new cjs.Rectangle(0,0,728,90), null);


// stage content:
(lib.FY22Q4_CC_Student_Blank_PT_PT_DCOGeneralPathfinders_ST_728x90 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = false; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// border
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,2,0,3).p("Eg43gHBMBxvAAAIAAODMhxvAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(80));

	// logo
	this.instance = new lib.logo();
	this.instance.setTransform(29.75,45.25,1.2756,1.2996,0,0,0,14.7,20.2);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({regX:14.8,regY:20.3,scaleX:1.2273,scaleY:1.2496,x:33.15,y:45.35,alpha:1},14,cjs.Ease.get(1)).wait(66));

	// txt1
	this.instance_1 = new lib.txt1();
	this.instance_1.setTransform(186.8,62.3,1,1,0,0,0,119.8,54.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(9).to({_off:false},0).to({x:196.8,alpha:1},15,cjs.Ease.get(1)).wait(56));

	// txt2
	this.instance_2 = new lib.txt2();
	this.instance_2.setTransform(182,72,1,1,0,0,0,115,12);
	this.instance_2.alpha = 0;
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(29).to({_off:false},0).to({x:192,alpha:1},15,cjs.Ease.get(1)).wait(36));

	// cta
	this.instance_3 = new lib.cta();
	this.instance_3.setTransform(373.75,44.45,0.6965,0.6972,0,0,0,52.8,19.3);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;
	new cjs.ButtonHelper(this.instance_3, 0, 1, 2, false, new lib.cta(), 3);

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(29).to({_off:false},0).to({x:353.75,alpha:1},15,cjs.Ease.get(1)).wait(36));

	// card
	this.instance_4 = new lib.card_1();
	this.instance_4.setTransform(516.65,147.9,0.511,0.5111,0,0,0,150,125);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(59).to({_off:false},0).to({scaleX:1,scaleY:1,x:260,y:125},20,cjs.Ease.get(1)).wait(1));

	// resume
	this.instance_5 = new lib.resume_1();
	this.instance_5.setTransform(264,215,1,1,0,0,0,150,125);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(44).to({_off:false},0).to({y:125},20,cjs.Ease.get(1)).wait(16));

	// bg
	this.instance_6 = new lib.bg();
	this.instance_6.setTransform(0,0,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(80));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(292.7,4.4,549.3,175.6);
// library properties:
lib.properties = {
	id: 'F452382931704EAC9F1999B2D4BF8E6A',
	width: 728,
	height: 90,
	fps: 30,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/bg.jpg?1673555270899", id:"bg"},
		{src:"images/card.png?1673555270899", id:"card"},
		{src:"images/resume.png?1673555270899", id:"resume"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['F452382931704EAC9F1999B2D4BF8E6A'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;